"""Utilities for applying patches generated by the Fixer agent."""
from __future__ import annotations

import logging
import subprocess
from pathlib import Path

LOGGER = logging.getLogger(__name__)


class PatchApplicationError(RuntimeError):
    """Raised when a git patch fails to apply."""


def apply_patch(patch: str, cwd: str | Path = ".") -> None:
    """Apply a unified diff to the working tree using `git apply`."""
    if not patch.strip():
        raise PatchApplicationError("Empty patch content")
    proc = subprocess.run(
        ["git", "apply", "-"],
        input=patch.encode(),
        cwd=str(cwd),
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        LOGGER.error("git apply failed: %s", proc.stderr.decode())
        raise PatchApplicationError(proc.stderr.decode())
    LOGGER.info("Patch applied successfully")
