---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	planner(planner)
	requester(requester)
	fixer(fixer)
	executor(executor)
	tester(tester)
	sonar(sonar)
	deployment(deployment)
	__end__([<p>__end__</p>]):::last
	__start__ --> planner;
	executor --> tester;
	fixer --> executor;
	planner --> requester;
	requester --> fixer;
	sonar --> deployment;
	tester --> sonar;
	deployment --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
